name    'erwbgy-ccfe'
version '0.1.1'
source 'https://github.com/erwbgy/puppet-ccfe'
author 'erwbgy'
license 'Apache License, Version 2.0'
summary 'Create Curses Command Front-end (CCFE) menus'
description 'Create Curses Command Front-end (CCFE) menus'
project_page 'http://erwbgy.github.com/puppet-ccfe'
